//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.ServiceCenter.tt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<DeviceType> DeviceType { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeePosition> EmployeePosition { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderFulfillment> OrderFulfillment { get; set; }
        public virtual DbSet<OrderService> OrderService { get; set; }
        public virtual DbSet<Part> Part { get; set; }
        public virtual DbSet<PartCategory> PartCategory { get; set; }
        public virtual DbSet<PartInServiceCenter> PartInServiceCenter { get; set; }
        public virtual DbSet<ServiceAppliance> ServiceAppliance { get; set; }
        public virtual DbSet<ServiceCenter> ServiceCenter { get; set; }
        public virtual DbSet<ServiceCenterBrand> ServiceCenterBrand { get; set; }
        public virtual DbSet<ServiceCenterDeviceType> ServiceCenterDeviceType { get; set; }
        public virtual DbSet<ServiceDetails> ServiceDetails { get; set; }
        public virtual DbSet<ServiceType> ServiceType { get; set; }
    }
}
