//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.ServiceCenter.tt
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCenterBrand
    {
        public int id { get; set; }
        public int brandId { get; set; }
        public int serviceCenterId { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual ServiceCenter ServiceCenter { get; set; }
    }
}
